// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Milestone2.SecondApplication.Models;

public partial class Car
{
    public string Vin { get; set; }

    public string Year { get; set; }

    public int MakeId { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public string Type { get; set; }

    public virtual ICollection<CarOwnership> CarOwnerships { get; set; } = new List<CarOwnership>();

    public virtual Make Make { get; set; }

    public override string ToString()
    {
        return $"{Vin}-{Year}-{Model}-{Make.BrandName} ";
    }
}