// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Milestone2.SecondApplication.Models;

public partial class Make
{
    public int MakeId { get; set; }

    public string BrandName { get; set; }

    public string Ceoname { get; set; }

    public string FoundingYear { get; set; }

    public string WebsiteLink { get; set; }

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public override string ToString()
    {
        return BrandName;
    }
}